### ISSUE TITLE
Training Details for ImageClef Dataset

### ISSUE THREAD

**Issue by vinodkkurmi** [thuml/PADA#2]
Could you share the dataset information(which examples taken for the training for both source and target) about all 6 transfer task?

**Comment by caozhangjie** [comment]
We do no experiments on ImageClef since the domain gap is not as large as VisDA and the classes is not as many as Office, Office-Home and ImageNet-Caltech. For Office, Office-Home and ImageNet-Caltech, we release the lists. For VisDA, you can construct the list with the description in our paper. (It is not released since the lists are too large)
